### ISSUE TITLE
Specify minimum supported clang (and maybe also gcc) version

### ISSUE THREAD

**Issue by bluewww** [riscv/riscv-arch-test#155]
We should say something about what kind of compiler versions are required to run `riscv-compliance.`

**Comment by allenjbaum** [comment]
This was filed because Clang didn't support a test program   written in assembler. IT isn't clear what assembler features Clang wasn't supporting at that time, but it seems like a Clang issue, and nothing that the Architectural tests have any control over (unless we are using some GCC feature that Clang does not and will not support in the future).

In addition: our plan is to deploy tests in a Docker image with all the tools required included, which may obviate any requirement for Clang.

So, I don't think this is a question that can be answered by us, and possibly won't need to be answered.
